---
title: "Structures List Tuples"
subtitle: "Module 2: Data Structures"
format: html
---

# Data Structures: Lists

Lists are a fundamental data structure in Python that allow you to store and manipulate collections of items. In this section, we will explore the basics of lists.

## Creating Lists






You can create a list in Python by enclosing a comma-separated sequence of items within square brackets.

```{python}
food = ["apple", "sandwich", "banana"]

print(food[1])
```

```{python}
print()  # calling a function
print[]  # indexing a list
```

```{python}
food = ["apple", "sandwich", "banana"] + ["pizza"]

print(food[1:4])
```

```{python}
v = [1, 2, 3]
u = [4, 5, 6]

print(v + u)
```

```{python}
u = "123"
v = "456"

print(u + v)
```

A list can contain **any** type of data. You can even mix different types.

```{python}
#| eval: false

```

In fact, you can do **nested lists**: one list inside another. This is the basis to create matrices.

```{python}
list_of_lists = [
    [1, 2, 3],
    [4, 5],
    [6, 7, 8]
]

print(list_of_lists[1][0])
```

---

## Properties of Lists

### Ordered

Lists in Python are ordered, which means that the elements in a list have a specific order, and this order is maintained. You can access elements in a list by their position or index within the list. The order of elements is significant because it allows you to perform operations on the elements in a specific sequence.

Remember that Python uses zero-based indexing, which means that the first element has an index of 0, the second has an index of 1, and so on. You can access elements in a list by referring to their index.

```{python}
#| eval: false

```

```{python}
#| eval: false

```

We can also slice lists, the same way we did with strings.

```{python}
#| eval: false

```

To index and access an element inside a nested list:

```{python}
#| eval: false

```

### Mutable

In Python, lists are mutable, which means that you can change their contents after they are created. This mutability allows you to add, remove, or modify elements within a list.

```{python}
print(food)

food[1] = "strawberry"

print(food)
```

Because lists are mutable, we can use **methods** to modify them. We will learn about these methods later!

### Duplicate Elements

Lists in Python can contain duplicate elements, which means that you can have the same value multiple times in a list. Duplicate elements can be useful in various situations, such as when you need to store multiple occurrences of the same data.

```{python}
[0, 1, 1, 2]
```

---

## Operations with Lists

Lists are a type of *sequence* in Python, similar to strings. If you remember how operations work with strings, you'll find it easy to work with lists!

We cannot sum an element to a list.

```{python}
#| eval: false

```

But we can sum two lists. This will concatenate them.

```{python}
#| eval: false

```

What happens if we multiply a list by a number? The same that happens to strings: the list gets repeated.

```{python}
#| eval: false

```

The function `len` will tell us the size of a list.

```{python}
#| eval: false

```

If we are working with nested lists, `len` will give the size of the outter-most list.

```{python}
#| eval: false

```

---

## Built-in List Methods



In Python, when you use a list method, you don't need to assign the result to a new variable because list methods typically operate directly on the list itself (**in-place**). Here's why you don't need to assign the result to a variable:

- **Mutability of Lists:** Lists in Python are mutable, which means you can modify them in place. When you call a list method, it modifies the original list directly.

- **No Need for Reassignment:** Since list methods modify the original list, there's no need to reassign the modified list to a new variable. The changes are made to the list object that you called the method on.

Python provides a variety of built-in methods to work with lists. Let's explore some of the most commonly used methods.

The `append()` method adds an item to the end of the list.

```{python}
#| eval: false

```

The `extend()` method adds elements from another iterable to the end of the list.

```{python}
#| eval: false

```

The `insert()` method inserts an item at a specified position in the list.

```{python}
#| eval: false

```

The `remove()` method removes the first occurrence of a specific value from the list.

```{python}
#| eval: false

```

The `pop()` method removes and returns an item at a specified position.

```{python}
#| eval: false

```

The `index()` method finds the index of the first occurrence of a value.

```{python}
#| eval: false

```

The `count()` method counts the number of occurrences of a specific value.

```{python}
#| eval: false

```

The `sort()` method sorts the list in ascending order.

```{python}
#| eval: false

```

The `reverse()` method reverses the order of items in the list.

```{python}
#| eval: false

```

The `clear()` method removes all items from the list.

```{python}
#| eval: false

```

---

[Practice some exercises here!](https://drive.google.com/file/d/1uwHBMmKv1rfujqPTAoVojDHUcXLSD5pw/view?usp=sharing)

---

# Data Structures: Tuples

Having understood lists, grasping the concept of tuples becomes straightforward. They function similarly, with only a few subtle distinctions.

```{python}
#| eval: false

```

```{python}
#| eval: false

```

Tuples are **ordered**, just like lists.

```{python}
#| eval: false

```

Tuples can contain duplicate elements too.

```{python}
#| eval: false

```

However, tuples are **not mutable**.

```{python}
#| eval: false

```

Tuples, being immutable, lack many of the methods available for lists.

So, why would we choose to use tuples?

- **Safety:** Because tuples are immutable, they provide a level of data protection. You can be certain that the data won't be accidentally modified elsewhere in your program.

- **Multiple Returns:** Functions in Python can return multiple values using tuples. This allows for returning more than one piece of information easily.

::: {.callout-note}
## Exercise

Define a function named `multiplication_and_division` that, given two numbers, returns both the multiplication and the division of them.

```{python}
#| eval: false

```

:::

---

[Practice some exercises here!](https://drive.google.com/file/d/1uwHBMmKv1rfujqPTAoVojDHUcXLSD5pw/view?usp=sharing)

---

## Summary

| Data Structure | Ordered | Mutable | Duplication |
|----------------|--------------------------|---------|----------------------|
| List           | ✅                       | ✅     | ✅                  |
| Tuple          | ✅                       | ❌     | ✅                  |

