---
title: "Fundamentals Recursion"
subtitle: "Module 1: Python Fundamentals"
format: html
---

[Review time!](https://drive.google.com/file/d/1AG5_-a8AtFjUCYEruLzeQI2NOLyVKQVS/view?usp=drive_link)

---

## Keyword Arguments in Python Functions


```{python}
#| eval: false

```


Keyword arguments are passed to a function using a keyword identifier followed by a value. Unlike positional arguments, which rely on their order, keyword arguments are associated with parameter names, making it clear which value corresponds to which parameter.

Using keyword arguments provides flexibility in function calls, as you can specify values for specific parameters while leaving others with default values.

```python
def <function_name>(<positional_argument>, <keyword_argument>=<default_value>):
  <code_of_the_function>
  return <output>
```

Keyword arguments always come after positional arguments, never before them.

```{python}
# This function computes the square root by default
# but we can choose the order of the root with `n`
def root(x, n=2):
  return x**(1/n)
```

```{python}
print(root(9))
```

```{python}
root(4, n=4)
```

```{python}
def root(x, n=2):
  return x**(1/n)

print(root(9, 3))
```

**Example.** How would you write a Python function that greets the user and allows them to customize the greeting message? Write it so that, if no greeting is given, defaults to "Hello".

```{python}
#| eval: false

```

**Example.** Build a calculator function calculate that accepts three arguments: `num1`, `num2`, and the keyword argument `operation`. The function should perform the specified operation (addition, subtraction, multiplication, or division) on `num1` and `num2` and return the result. If no operation is given, defaults to addition.

```{python}
#| eval: false

```

---

# Docstrings

A docstring is a string that provides documentation for a function or module. It helps developers understand how to use the code. Docstrings are enclosed in triple quotes.

**Example.** Add a docstring to our previous `greet` function.

```{python}
def greet(name):
  """
  This function greets a person.

  Parameters
  ----------
  name : str
    The name of the person to greet.

  Returns
  -------
  str
    A greeting message.
  """
  return f"Hello, {name}!"
```

# Type Hints

Type hints are a way to specify the types of function arguments and return values in your code. While Python does not enforce these types at runtime, they serve as valuable documentation for understanding code.

To add a type hint for function arguments, simply place a colon `:` after the parameter name. To hint the output type, use a right arrow `->`.

**Example.** Implement an addition function with type hints.

```{python}
def add(a: int, b: int) -> int:
  return a + b
```

```{python}
#| eval: false
def square_solver(a: int, b: int, c: int) -> float:
  """
  This function solves a cuadratic equation in the form
  a x2 + b x + c = 0

  Parameters
  ----------
  a : int
    Number that multiplies x^2
  b
  ...

  Returns
  -------
  float
    The value of x that meets that equation
  """
```

**Example.** Implement a function that takes a student's name and their grade, then returns a text saying whether they passed or not. Include a docstring and type hints.

```{python}
def check_pass(name: str, grade: int) -> str:
  """
  This function returns a message saying if the student
  has passed or not.

  Parameters
  ----------
  name : str
    The student's name
  grade : int
    The student's score, between 0 and 10

  Returns
  -------
  str
    Message saying whether the student passed or not
  """
  if grade >= 5:
    return f"{name} has passed!"
  else:
    return f"{name} has failed"
```

Both docstrings and type hints can be seen on Google Colaboratory when we hover our cursor on the function name. Try it now!

```{python}
check_pass("Sebastian", 10)
```

---

# Recursive Functions

You can use one function inside another!

**Example.** Implement a function `closest_lower_prime(m)` that takes a number `m` and returns the closest prime number that is lower than `m`. You can use the `is_prime()` function you previously defined to help you.

```{python}
def factorial(number: int) -> int:
  if number >= 2:
    return number * factorial(number - 1)
  else:
    return 1

print(factorial(5))
```

**Example.** Implement a function that takes a list of numbers and prints the closest prime number that is lower than each of them, using a message like "x is the closest lower prime number to n".

```{python}
#| eval: false

```

In fact, a function can even **call itself**. A **recursive function** is a function that solves a problem by breaking it down into smaller instances of the same problem, calling itself with these smaller inputs.

Each recursive function needs a base case (a condition under which it stops calling itself) to avoid an infinite loop. When the base case is reached, the function begins to return its results, eventually building back up to the original call.

For example, the factorial function is often defined recursively:

```{python}
#| eval: false

```

This approach is elegant and powerful, especially for problems that have a naturally recursive structure, like computing Fibonacci numbers, traversing trees, or solving puzzles like the Tower of Hanoi.

::: {.callout-note}
## Exercise

Write a recursive function `fibonacci(n)` that returns the `n`-th number in the Fibonacci sequence, defined as:

- $F(0) = 0$  
- $F(1) = 1$  
- $F(n) = F(n-1) + F(n-2) for n \geq 2$

```{python}
#| eval: false

```

:::

::: {.callout-note}
## Exercise

Write a recursive function `hanoi(n, source, target, auxiliary)` that prints the steps to solve the Tower of Hanoi puzzle for `n` disks. Rules:

- There are three towers: A, B and C.
- There are $n$ disks of different sizes.
- All disks start at tower A, forming a pyramid (bigger at bottom, smaller at top).
- You need to move all disk to tower C.
- Only one disk can be moved at a time.
- A larger disk cannot be placed on top of a smaller one.

```{python}
#| eval: false

```

:::

---

# Generator Functions

In Python, a generator function is a special type of function that allows you to generate a sequence of values on-the-fly. Unlike regular functions that compute all values at once and store them in memory, generator functions generate values one at a time, which can be more memory-efficient. This session will introduce us to generator functions and the `yield` statement.

Generator functions are defined like regular functions but use the `yield` statement instead of `return`. When a generator function is called, it returns a generator object, which can be iterated over to retrieve the values generated by the function.

Let's start by defining a simple generator function that generates a sequence of even numbers:

```{python}
def generate_even_numbers(limit: int) -> int:
  """
  This is a generator function that yields even numbers
  less than a specified limit

  Parameters
  ----------
  limit : int

  Returns
  -------
  int
    Even number less than `limit`
  """
  n = 0
  while n < limit:
    print(f"  [Function enters loop and yields {n}]")
    yield n
    n += 2
    print("  [Function moves to next loop]")
```

```{python}
def fibonacci():
  a = 1
  b = 1
  for idx in range(10000):
    new = a + b
    a = b
    b = new
    yield new

generator = fibonacci()
```

```{python}
print(next(generator))
```

What is the output of this expression? Lets see:

```{python}
x = generate_even_numbers(10)

print(x)
```

```{python}
x = generate_even_numbers(10)

print(type(x))
```

The output of a **generator function** (a function that uses yield) is a **generator**.

⚠ You cannot operate with generators!

```{python}
x = generate_even_numbers(10)
y = 3

print(x + y)
```

## Using a Generator

To use a generator, you can iterate over it using a `for` loop or by explicitly calling `next()` to retrieve the next value.

Here's how you can use our `generate_even_numbers` function:

```{python}
even_generator = generate_even_numbers(10)
print(f"Type of `even_generator`: {type(even_generator)}")

# This code will print even numbers from 0 to 8
print("Start looping on `even_generator`")
for num in even_generator:
  print(f"  `even_generator` returns {num}")
  print("  Next step!\n")
print("End of loop")
```

Alternatively, this is how we use the `next` statement:

```{python}
even_generator = generate_even_numbers(10)

num = next(even_generator)
print(f"`even_generator` returns {num}\n")

num = next(even_generator)
print(f"`even_generator` returns {num}\n")

num = next(even_generator)
print(f"`even_generator` returns {num}")
```

## Difference between `return` and `yield` Python

The `yield` keyword in Python is similar to a `return` statement used for returning values in Python which returns a generator object to the one who calls the function which contains `yield`, instead of simply returning a value. The main difference between them is, the `return` statement terminates the execution of the function. Whereas, the `yield` statement only pauses the execution of the function. Another difference is `return` statements are never executed. Whereas, `yield` statements are executed when the function resumes its execution.

Advantages of `yield`:
- Using `yield` keyword is highly memory efficient, since the execution happens only when the caller iterates over the object.
- As the variables states are saved, we can pause and resume from the same point, thus saving time.

Disadvantages of `yield`:

- Sometimes it becomes hard to understand the flow of code due to multiple times of value return from the function generator.
- Calling of generator functions must be handled properly, else might cause errors in program.

[Reference](https://www.geeksforgeeks.org/python-yield-keyword/)

What will happen with this function?

```{python}
def generate_even_numbers(limit: int) -> int:
  n = 0
  while n < limit:
    print(f"  [Function enters loop and returns {n}]")
    return n
    n += 2
    print("  [Function moves to next loop]")
```

```{python}
x = generate_even_numbers(10)
print(f"Type of output is {type(x)}")
print(f"x is {x}")
```

---

**Example.** Lets use our knowledge of functions to solve the quadratic equation we saw during our first day of class!

$$f(x) = a \cdot x^2 + b \cdot x + c$$

But this time, $a=1$, $b=1$, $c=-6$ are keyword arguments.

```{python}
#| eval: false

```

**Example. Decay of a Radioactive Element**

In this exercise, you will create a Python function to model the radioactive decay of a specific element over time. Radioactive decay is a common phenomenon in nuclear physics and has applications in various fields, including radiometric dating and nuclear medicine.

Consider a radioactive element with a known half-life (the time it takes for half of the element to decay) represented as half_life (in years). The number of radioactive atoms at any given time can be described by the formula:

$$N(t) = N_0 * (1/2)^{(t / \text{half_life})}$$

Where:
- $N(t)$ is the number of radioactive atoms at time $t$.
- $N_0$ is the initial number of radioactive atoms at time $t = 0$.

Your task is to create a Python function `radioactive_decay(n0, half_life, t)` that calculates the number of radioactive atoms remaining at a specific time `t` using the provided parameters. The function should take the following keyword arguments:

- `n0`: Initial number of radioactive atoms.
- `half_life`: Half-life of the radioactive element in years (default value: 5730 years).
- `t`: Time (in years) at which you want to calculate the remaining atoms (default value: 500 years).

Your function should return the remaining number of radioactive atoms at time `t`.

```{python}
#| eval: false

```

**Carbon-14 Dating.** Carbon-14 is a radioactive isotope used for radiometric dating. It has a half-life of approximately 5,730 years.

```{python}
#| eval: false

```

**Uranium-238 Decay.** Uranium-238 is another radioactive isotope with a much longer half-life, approximately 4.468 billion years.

```{python}
#| eval: false

```
