---
title: "Arithmetic Operations in Python"
format: html
execute:
  error: true
---

# Fundamentals: Arithmetic Operations in Python


We can use Python as a calculator.

```{python}
print(5 + 8 + 3)
```

Note that the extra spaces are added to make the code more readable.
`5 + 8 + 3` works just as well as `5+8+3`. And it is considered good style. Use the extra spaces in all your Notebooks.

Below are all the possible arithmetic operations you can do:

```{python}
# Sum
print(5 + 2)
```

```{python}
# Subtraction
print(5 - 2)
```

```{python}
# Multiplication
print(5 * 2)
```

```{python}
# Division
print(5 / 2)
```

```{python}
# Exponentiation
print(5 ** 2)
```

```{python}
# Quotient
print(5 // 2)
```

```{python}
# Remainder
print(5 % 2)
```

::: {.callout-note}
## Exercise

You store 10K euros in a bank account. Compute the compound interest after 10 years at a rate of 5%.


:::

::: {.callout-tip collapse="true"}
## Solution

```{python}
print(10000 * (1 + 0.05) ** 10)
```

:::

The **order of operations** in Python is the same as in arithmetic. First, you compute parentheses, then exponents, then you multiply and divide (from left to right), and finally, you add and subtract (from left to right).

::: {.callout-note}
## Exercise

Convert 32 degrees Celsius into Farenheit.

$$(F - 32) \cdot 5/9 = C$$


:::

::: {.callout-tip collapse="true"}
## Solution

```{python}
print(32 * 9 / 5 + 32)
```

:::

::: {.callout-note}
## Exercise

Fix this code to compute a square root.


```{python}
#| eval: false
print(4 ** 1/2)
```

:::

::: {.callout-tip collapse="true"}
## Solution

The code runs, but it computes $(4^1)/2$ because exponentiation happens before division. You need parentheses around the exponent.

```{python}
print(4 ** (1/2))
```

:::

---
