---
title: "Review: Flow Control"
subtitle: "Module 1: Python Fundamentals"
format: html
execute:
  enabled: false  # dont execute code during render
---

::: {.callout-note}
## When Your Clause Never Happens

Which of the following `if` statements can never happen, no matter what values are used? Assume that we are using positive values for `apples`, `bananas`, and `friends`.

```{python}
# We have apples and bananas. We want to give at least one fruit to each friend.
# Do we have enough fruits? Are the apples enough? Are the bananas?

apples = 10
bananas = 5
friends = 15

if (apples + bananas) >= friends:
  print("We have enough fruits for our friends!")
elif apples >= friends:
  print("We have enough apples for our friends!")
elif bananas >= friends:
  print("We have enough bananas for our friends!")
else:
  print("We don't have enough fruit for our friends!")
```

:::

::: {.callout-tip collapse="true"}
## Answer

The second and third `elif` statements will never happen because if we have enough apples or bananas, then we would have enough fruits in total. The first `if` statement will always be true if either of the `elif` statements is true.
:::

::: {.callout-note}
## Modifying a Variable Inside an `if` Statement

What is going to be the final value of `x`?

```{python}
x = 5

condition = x**2 < 10

if condition:
  x = x + 1
else:
  x = x + 3

x = x / 2

print(x)
```

| Once you have an answer, copy the code into your own notebook and run it to check your answer.
:::

::: {.callout-note}
## Another Comparison

What is going to be the output of this cell?

```{python}
years = "5"

if years > 0:
  print(f"I am {years} years old")
```

| Once you have an answer, copy the code into your own notebook and run it to check your answer.

:::

::: {.callout-note}
## One Last Comparison

Look at the following piece of code and explain why it fails.

```{python}
# Create a code that checks if a number a is divisible by another b. The output
# should be a message like "a is divisible by b"

a = 10
b = 2
# Expected output: Yes

# (a, b) are divisible if the remainder of a/b is 0
if a % b = 0:
  print(f"{a} is divisible by {b}")
```

:::

::: {.callout-tip collapse="true"}
## Answer
The code fails because the comparison operator is `==`, not `=`. The single equals sign is used for assignment, while the double equals sign is used for comparison. The correct code should be:
:::

---
